name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install package dependencies
        run: npm ci
      - run: npm run type-check
      - run: npm run lint
      - name: install pandoc and latex
        run: |
          sudo apt-get update
          wget https://github.com/jgm/pandoc/releases/download/$pandoc_ver/pandoc-$pandoc_ver-1-arm64.deb -O pandoc.deb
          dpkg -i pandoc.deb && rm pandoc.deb 
          sudo apt-get install texlive-latex-extra -y
      - name: Run unit tests
        run: npm test
      - name: Build
        run: npm run build
